# Generated by Django 4.2.3 on 2023-08-17 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_reviewdb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewdb',
            name='User',
        ),
        migrations.AddField(
            model_name='reviewdb',
            name='selectuser',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
